name: Z3 Trace Log Generator for at least v4.9.0 

on:
  push:
    branches: [ "main" ]
    # only triggers job when smt2 files are changed (added/removed/modified) in a push
    paths:
      - '**/*.smt2'

  # job can also be triggered manually on GitHub
  workflow_dispatch:

jobs:
  generate_log:
    strategy: 
      matrix:
        z3version: ['4.9.0','4.12.2'] 
    
    # for versions of Z3 at least 4.9.0 we need v1.3 of the GitHub action, for older versions of Z3, 1.2.2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # this copies the whole repository
        with:
          fetch-depth: 0 # needed, see GitHub Action "Changed Files"

      - name: Install Z3 
        uses: pavpanchekha/setup-z3@v1.3 # see GitHub Action "Install Z3"
        with:
          version: ${{ matrix.z3version }} 

      # this fetches all changed (added/modified) smt2 files in the repository 
      - name: Fetch changed smt2 files
        id: changed-smt2-files
        uses: tj-actions/changed-files@v38.2.0 # see GitHub Action "Changed Files"
        with: 
          files_yaml: |
            smt:
              - '**/*.smt2'

      - name: Run Z3 solver on changed smt2 files and upload logs 
        run: |
          # Create the 'logs' directory
          mkdir logs

          # Loop through the files
          for file in ${{ steps.changed-smt2-files.outputs.smt_all_changed_files }}; do
              echo "Processing $file"
              
              # Get the filename without extension
              base_name=$(basename "${file%.*}")
              
              # Run Z3 solver for the file and save the log in the 'logs' directory
              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file
          done

      - name: List log files
        run: |
          ls -l logs/*.log

      - name: Upload log files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: logs
          path: logs/*.log


